name: fitness_tracker_fakhim_app
description: Techne Fitness Platform - منصة تكنيك للياقة
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State management
  provider: ^6.1.2
  # Charts
  fl_chart: ^0.68.0
  # Fonts
  google_fonts: ^6.2.1
  # Storage (simple)
  shared_preferences: ^2.2.2
  # Local DB
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  # Notifications
  flutter_local_notifications: ^17.2.2
  # Home widgets
  home_widget: ^0.7.0
  # Health
  health: ^11.1.1
  # Utils
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
